<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY hellip "&#x2026;">
] >

<issue num="2497" status="New">
<title>Use of <tt>uncaught_exception()</tt></title>
<section><sref ref="[ostream::sentry]"/></section>
<submitter>Roger Orr</submitter>
<date>8 May 2015</date>
<priority>3</priority>

<discussion>
<p>
In the current <sref ref="[ostream::sentry]"/>, p4 refers to the now deprecated <tt>std::uncaught_exception()</tt>: 
D.9 [depr.uncaught].
</p>
<blockquote>
<p>
If <tt>((os.flags() &amp; ios_base::unitbuf) &amp;&amp; !uncaught_exception() &amp;&amp; os.good())</tt> is true, calls
<tt>os.rdbuf()->pubsync()</tt>.
</p>
</blockquote>
<p>
This needs to be changed, for example to use <tt>std::uncaught_exceptions()</tt> and to capture the value on entry and 
compare with the saved value on exit.
</p>

<note>2015-06, Telecom</note>
<p>
JW: I already added an 's' here to make it use the new function, but that doesn't resolve Roger's suggestion to capture the value on entry and check it.
</p>
</discussion>

<resolution>
</resolution>

</issue>
